import 'package:flutter/material.dart';

/* Rectangle noticia1 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNoticia11Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 394.0,
      height: 280.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/ff962e27e0d80ebd4cd8828cd2c4d061570c25b0.png",
          color: null,
          fit: BoxFit.cover,
          width: 394.0,
          height: 280.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
