import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget38/generated/GeneratedRectangle15Widget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget38/generated/GeneratedBotonWidget3.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget38/generated/GeneratedAyudaysoportetcnicoWidget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget38/generated/GeneratedFormasdepagoWidget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget38/generated/GeneratedMenuinferiorWidget17.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget38/generated/GeneratedRectangle14Widget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget38/generated/GeneratedIdiomaWidget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget38/generated/GeneratedAjustesWidget41.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget38/generated/GeneratedMenusuperiorWidget14.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget38/generated/GeneratedRectangle13Widget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget38/generated/GeneratedComponent4Widget3.dart';

/* Frame Ajustes
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAjustesWidget38 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 242, 242, 242),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 831.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 55.0,
                child: GeneratedMenuinferiorWidget17(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuperiorWidget14(),
              ),
              Positioned(
                left: 17.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 75.0,
                child: GeneratedRectangle15Widget2(),
              ),
              Positioned(
                left: 17.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 75.0,
                child: GeneratedRectangle14Widget2(),
              ),
              Positioned(
                left: 17.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 75.0,
                child: GeneratedRectangle13Widget2(),
              ),
              Positioned(
                left: 72.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 70.0,
                child: GeneratedBotonWidget3(),
              ),
              Positioned(
                left: 119.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 68.0,
                child: GeneratedAjustesWidget41(),
              ),
              Positioned(
                left: 96.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 40.0,
                child: GeneratedFormasdepagoWidget2(),
              ),
              Positioned(
                left: 158.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 43.0,
                child: GeneratedIdiomaWidget2(),
              ),
              Positioned(
                left: 37.0,
                top: 462.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 40.0,
                child: GeneratedAyudaysoportetcnicoWidget2(),
              ),
              Positioned(
                left: 15.0,
                top: 542.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 75.0,
                child: GeneratedComponent4Widget3(),
              )
            ]),
      ),
    ));
  }
}
