import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget21/generated/GeneratedMenusuperiorWidget15.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget21/generated/GeneratedScrollhoriozintalWidget3.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget21/generated/GeneratedMenuinferiorWidget18.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget21/generated/GeneratedContratosWidget3.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget21/generated/GeneratedFinanzasWidget3.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget21/generated/GeneratedGroup4Widget3.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget21/generated/GeneratedAhorrodeenergaWidget3.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget21/generated/GeneratedDesarrollosocialWidget3.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget21/generated/GeneratedBuscadorWidget3.dart';

/* Frame Inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInicioWidget21 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 242, 242, 242),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 831.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 55.0,
                child: GeneratedMenuinferiorWidget18(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuperiorWidget15(),
              ),
              Positioned(
                left: 42.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 60.0,
                child: GeneratedBuscadorWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 254.0,
                child: GeneratedScrollhoriozintalWidget3(),
              ),
              Positioned(
                left: 74.0,
                top: 496.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 243.3265380859375,
                child: GeneratedGroup4Widget3(),
              ),
              Positioned(
                left: 74.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 36.0,
                child: GeneratedContratosWidget3(),
              ),
              Positioned(
                left: 246.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 36.0,
                child: GeneratedFinanzasWidget3(),
              ),
              Positioned(
                left: 74.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 64.0,
                child: GeneratedAhorrodeenergaWidget3(),
              ),
              Positioned(
                left: 211.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 33.0,
                child: GeneratedDesarrollosocialWidget3(),
              )
            ]),
      ),
    ));
  }
}
