import 'package:flutter/material.dart';

/* Rectangle noticia2 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNoticia21Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 379.0,
      height: 311.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/72663a2db18f9b7d47a01df3cb9c43c9f2108742.png",
          color: null,
          fit: BoxFit.cover,
          width: 379.0,
          height: 311.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
