import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget14/generated/GeneratedMenusuperiorWidget10.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget14/generated/GeneratedAhorrodeenergaWidget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget14/generated/GeneratedBuscadorWidget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget14/generated/GeneratedDesarrollosocialWidget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget14/generated/GeneratedMenuinferiorWidget12.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget14/generated/GeneratedContratosWidget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget14/generated/GeneratedGroup4Widget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget14/generated/GeneratedScrollhoriozintalWidget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatediniciowidget14/generated/GeneratedFinanzasWidget2.dart';

/* Frame Inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInicioWidget14 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 242, 242, 242),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 831.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 55.0,
                child: GeneratedMenuinferiorWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuperiorWidget10(),
              ),
              Positioned(
                left: 42.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 60.0,
                child: GeneratedBuscadorWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 254.0,
                child: GeneratedScrollhoriozintalWidget2(),
              ),
              Positioned(
                left: 74.0,
                top: 496.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 243.3265380859375,
                child: GeneratedGroup4Widget2(),
              ),
              Positioned(
                left: 74.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 36.0,
                child: GeneratedContratosWidget2(),
              ),
              Positioned(
                left: 246.0,
                top: 590.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 36.0,
                child: GeneratedFinanzasWidget2(),
              ),
              Positioned(
                left: 74.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 64.0,
                child: GeneratedAhorrodeenergaWidget2(),
              ),
              Positioned(
                left: 211.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 189.0,
                height: 33.0,
                child: GeneratedDesarrollosocialWidget2(),
              )
            ]),
      ),
    ));
  }
}
