import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedbuscadorwidget8/generated/GeneratedSearchsharpWidget8.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedbuscadorwidget8/generated/GeneratedBuscarWidget8.dart';

/* Instance Buscador
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBuscadorWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(40.0),
        child: Container(
          width: 330.0,
          height: 60.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(40.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(40.0),
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 50.0,
                  top: 11.0,
                  right: null,
                  bottom: null,
                  width: 120.0,
                  height: 43.0,
                  child: GeneratedBuscarWidget8(),
                ),
                Positioned(
                  left: 280.0,
                  top: 10.0,
                  right: null,
                  bottom: null,
                  width: 40.0,
                  height: 40.0,
                  child: GeneratedSearchsharpWidget8(),
                )
              ]),
        ),
      ),
    ));
  }
}
