import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget24/generated/GeneratedAyudaysoportetcnicoWidget1.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget24/generated/GeneratedFormasdepagoWidget1.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget24/generated/GeneratedMenusuperiorWidget9.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget24/generated/GeneratedIdiomaWidget1.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget24/generated/GeneratedRectangle15Widget1.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget24/generated/GeneratedAjustesWidget27.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget24/generated/GeneratedComponent4Widget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget24/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget24/generated/GeneratedMenuinferiorWidget11.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget24/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget24/generated/GeneratedBotonWidget2.dart';

/* Frame Ajustes
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAjustesWidget24 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 242, 242, 242),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 831.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 55.0,
                child: GeneratedMenuinferiorWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuperiorWidget9(),
              ),
              Positioned(
                left: 17.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 75.0,
                child: GeneratedRectangle15Widget1(),
              ),
              Positioned(
                left: 17.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 75.0,
                child: GeneratedRectangle14Widget1(),
              ),
              Positioned(
                left: 17.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 75.0,
                child: GeneratedRectangle13Widget1(),
              ),
              Positioned(
                left: 72.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 70.0,
                child: GeneratedBotonWidget2(),
              ),
              Positioned(
                left: 119.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 68.0,
                child: GeneratedAjustesWidget27(),
              ),
              Positioned(
                left: 96.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 40.0,
                child: GeneratedFormasdepagoWidget1(),
              ),
              Positioned(
                left: 158.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 43.0,
                child: GeneratedIdiomaWidget1(),
              ),
              Positioned(
                left: 37.0,
                top: 462.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 40.0,
                child: GeneratedAyudaysoportetcnicoWidget1(),
              ),
              Positioned(
                left: 15.0,
                top: 542.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 75.0,
                child: GeneratedComponent4Widget2(),
              )
            ]),
      ),
    ));
  }
}
