import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget2/generated/GeneratedInputWidget5.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget2/generated/GeneratedInputWidget4.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget2/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget2/generated/GeneratedBOTONWidget3.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget2/generated/GeneratedCorreoelectrnicoWidget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget2/generated/GeneratedBienvenidoWidget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget2/generated/GeneratedContraseaWidget4.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget2/generated/GeneratedGroup1Widget2.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget2/generated/GeneratedOlvidastetucontraseaWidget2.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -204.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 660.0,
                height: 466.0,
                child: GeneratedGroup1Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 498.0,
                child: GeneratedRectangle1Widget2(),
              ),
              Positioned(
                left: 57.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 42.0,
                child: GeneratedContraseaWidget4(),
              ),
              Positioned(
                left: 57.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 256.0,
                height: 39.0,
                child: GeneratedCorreoelectrnicoWidget2(),
              ),
              Positioned(
                left: 83.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 64.0,
                child: GeneratedBienvenidoWidget2(),
              ),
              Positioned(
                left: 83.0,
                top: 685.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 28.0,
                child: GeneratedOlvidastetucontraseaWidget2(),
              ),
              Positioned(
                left: 47.0,
                top: 526.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedInputWidget4(),
              ),
              Positioned(
                left: 47.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedInputWidget5(),
              ),
              Positioned(
                left: 72.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 70.0,
                child: GeneratedBOTONWidget3(),
              )
            ]),
      ),
    ));
  }
}
