import 'package:flutter/material.dart';

/* Frame settings-sharp
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSettingssharpWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 25.0,
        height: 25.0,
      ),
    ));
  }
}
