import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget/generated/GeneratedOlvidastetucontraseaWidget.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget/generated/GeneratedInputWidget.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget/generated/GeneratedInputWidget1.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget/generated/GeneratedContraseaWidget.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget/generated/GeneratedCorreoelectrnicoWidget.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget/generated/GeneratedBienvenidoWidget.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget/generated/GeneratedBOTONWidget.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -204.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 660.0,
                height: 466.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 498.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 42.0,
                child: GeneratedContraseaWidget(),
              ),
              Positioned(
                left: 57.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 256.0,
                height: 39.0,
                child: GeneratedCorreoelectrnicoWidget(),
              ),
              Positioned(
                left: 83.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 64.0,
                child: GeneratedBienvenidoWidget(),
              ),
              Positioned(
                left: 83.0,
                top: 685.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 28.0,
                child: GeneratedOlvidastetucontraseaWidget(),
              ),
              Positioned(
                left: 47.0,
                top: 526.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedInputWidget(),
              ),
              Positioned(
                left: 47.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedInputWidget1(),
              ),
              Positioned(
                left: 72.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 70.0,
                child: GeneratedBOTONWidget(),
              )
            ]),
      ),
    ));
  }
}
