import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedperfilwidget86/generated/GeneratedMenuinferiorWidget40.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedperfilwidget86/generated/Generated1234Widget6.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedperfilwidget86/generated/GeneratedDaliaMartinezWidget6.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedperfilwidget86/generated/GeneratedFormadepagoWidget6.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedperfilwidget86/generated/GeneratedDomicilioWidget6.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedperfilwidget86/generated/GeneratedMenusuperiorWidget33.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedperfilwidget86/generated/GeneratedCalleSalpiconerosSaladosWidget6.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedperfilwidget86/generated/GeneratedVectorWidget241.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedperfilwidget86/generated/GeneratedColoniaApolo455Widget6.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedperfilwidget86/generated/GeneratedTarjetadedebitoWidget6.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedperfilwidget86/generated/GeneratedComponent2Widget6.dart';

/* Frame Perfil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPerfilWidget86 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 242, 242, 242),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 831.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 55.0,
                child: GeneratedMenuinferiorWidget40(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.37922705314009664;
                  double scaleX = (constraints.maxWidth * percentWidth) / 157.0;

                  double percentHeight = 0.17522321428571427;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 157.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.30917874396135264,
                        translateY: constraints.maxHeight * 0.14508928571428573,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget241())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuperiorWidget33(),
              ),
              Positioned(
                left: 121.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 34.0,
                child: GeneratedDaliaMartinezWidget6(),
              ),
              Positioned(
                left: 27.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 37.0,
                child: GeneratedDomicilioWidget6(),
              ),
              Positioned(
                left: 27.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 34.0,
                child: GeneratedCalleSalpiconerosSaladosWidget6(),
              ),
              Positioned(
                left: 27.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 34.0,
                child: GeneratedColoniaApolo455Widget6(),
              ),
              Positioned(
                left: 34.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 34.0,
                child: GeneratedFormadepagoWidget6(),
              ),
              Positioned(
                left: 27.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 34.0,
                child: GeneratedTarjetadedebitoWidget6(),
              ),
              Positioned(
                left: 49.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 37.0,
                child: Generated1234Widget6(),
              ),
              Positioned(
                left: 67.0,
                top: 655.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 40.0,
                child: GeneratedComponent2Widget6(),
              )
            ]),
      ),
    ));
  }
}
