import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget96/generated/GeneratedAjustesWidget99.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget96/generated/GeneratedRectangle16Widget5.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget96/generated/GeneratedRectangle14Widget6.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget96/generated/GeneratedRectangle15Widget6.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget96/generated/GeneratedAyudaysoportetcnicoWidget6.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget96/generated/GeneratedMenuinferiorWidget42.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget96/generated/GeneratedIdiomaWidget6.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget96/generated/GeneratedFormasdepagoWidget6.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget96/generated/GeneratedRectangle13Widget6.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget96/generated/GeneratedMenusuperiorWidget35.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget96/generated/GeneratedBotonWidget9.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedajusteswidget96/generated/GeneratedEnviarcomentariosWidget1.dart';

/* Frame Ajustes
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAjustesWidget96 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 242, 242, 242),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 831.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 55.0,
                child: GeneratedMenuinferiorWidget42(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuperiorWidget35(),
              ),
              Positioned(
                left: 17.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 75.0,
                child: GeneratedRectangle15Widget6(),
              ),
              Positioned(
                left: 17.0,
                top: 542.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 75.0,
                child: GeneratedRectangle16Widget5(),
              ),
              Positioned(
                left: 17.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 75.0,
                child: GeneratedRectangle14Widget6(),
              ),
              Positioned(
                left: 17.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 75.0,
                child: GeneratedRectangle13Widget6(),
              ),
              Positioned(
                left: 72.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 70.0,
                child: GeneratedBotonWidget9(),
              ),
              Positioned(
                left: 119.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 68.0,
                child: GeneratedAjustesWidget99(),
              ),
              Positioned(
                left: 96.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 40.0,
                child: GeneratedFormasdepagoWidget6(),
              ),
              Positioned(
                left: 158.0,
                top: 363.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 43.0,
                child: GeneratedIdiomaWidget6(),
              ),
              Positioned(
                left: 37.0,
                top: 462.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 40.0,
                child: GeneratedAyudaysoportetcnicoWidget6(),
              ),
              Positioned(
                left: 75.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 273.0,
                height: 40.0,
                child: GeneratedEnviarcomentariosWidget1(),
              )
            ]),
      ),
    ));
  }
}
