import 'package:flutter/material.dart';

/* Rectangle noticia3 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNoticia31Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 393.0,
      height: 261.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/b357cd66e65434284602b6b84b7bbaac4741720d.png",
          color: null,
          fit: BoxFit.cover,
          width: 393.0,
          height: 261.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
