import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedcomponent5widget/generated/GeneratedCambiaramodooscuroWidget4.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedcomponent5widget/generated/GeneratedRectangle16Widget6.dart';

/* Instance Component 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedComponent5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 382.0,
      height: 75.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle16Widget6(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8848167539267016;

                final double height =
                    constraints.maxHeight * 0.5333333333333333;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.07068062827225131,
                      y: constraints.maxHeight * 0.25333333333333335,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedCambiaramodooscuroWidget4(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
