import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget5/generated/GeneratedBienvenidoWidget5.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget5/generated/GeneratedOlvidastetucontraseaWidget5.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget5/generated/GeneratedRectangle1Widget5.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget5/generated/GeneratedInputWidget11.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget5/generated/GeneratedInputWidget12.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget5/generated/GeneratedContraseaWidget10.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget5/generated/GeneratedCorreoelectrnicoWidget5.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget5/generated/GeneratedBOTONWidget7.dart';
import 'package:flutterapp/proyecto_20figma_20cfeapp/generatedloginwidget5/generated/GeneratedGroup1Widget5.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -204.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 660.0,
                height: 466.0,
                child: GeneratedGroup1Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 498.0,
                child: GeneratedRectangle1Widget5(),
              ),
              Positioned(
                left: 57.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 42.0,
                child: GeneratedContraseaWidget10(),
              ),
              Positioned(
                left: 57.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 256.0,
                height: 39.0,
                child: GeneratedCorreoelectrnicoWidget5(),
              ),
              Positioned(
                left: 83.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 64.0,
                child: GeneratedBienvenidoWidget5(),
              ),
              Positioned(
                left: 83.0,
                top: 685.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 28.0,
                child: GeneratedOlvidastetucontraseaWidget5(),
              ),
              Positioned(
                left: 47.0,
                top: 526.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedInputWidget11(),
              ),
              Positioned(
                left: 47.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 40.0,
                child: GeneratedInputWidget12(),
              ),
              Positioned(
                left: 72.0,
                top: 759.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 70.0,
                child: GeneratedBOTONWidget7(),
              )
            ]),
      ),
    ));
  }
}
